Верстка приложения "список контактов"
Pavel2688/AndroidLessons pull request #2
Opened 2020-04-29 15:23 UTC by Pavel2688

Скриншоты списка контактов и деталей контакта:
![Android1](https://user-images.githubusercontent.com/57447822/80613056-d0e4ec80-8a4d-11ea-8aef-6fa1766b9d77.jpg)
![Android2](https://user-images.githubusercontent.com/57447822/80613785-c1b26e80-8a4e-11ea-8a60-40e0694f2111.jpg)

цвет для colorPrimary и colorAccent : #CDEEBC44      #DA28B958

2020-04-29 16:30 UTC, goblinr requested changes
Задание совсем не соответствует требованиям.
Необходимо было сделать 2 фрагмента.
Здесь же только одна 1 активность

2020-05-05 10:53 UTC, Pavel2688 commented
![android1](https://user-images.githubusercontent.com/57447822/81058363-5bf73400-8edf-11ea-87d7-1bb49c258c3a.jpg)
![android2](https://user-images.githubusercontent.com/57447822/81058462-8812b500-8edf-11ea-973c-e9906fc23f71.jpg)
Переделал все по ТЗ

2020-05-05 12:10 UTC, goblinr requested changes

2020-05-05 12:10 UTC, goblinr commented on app/src/main/java/user/pasha888/com/androidlessons/ContactListFragment.java
> +    public static final Kontakt[] kontakt = {
**K**ontakt -> **C**ontact**s**

2020-05-05 12:10 UTC, goblinr commented on app/src/main/java/user/pasha888/com/androidlessons/Kontakt.java
> +public class Kontakt {
Contact

2020-05-05 12:10 UTC, goblinr commented on app/src/main/java/user/pasha888/com/androidlessons/MainActivity.java
> +        this.setTitle("Список контактов");
Это не верно. Удалить

2020-05-05 12:10 UTC, goblinr commented on app/src/main/res/layout/activity_main.xml
> +  <LinearLayout
Ненужная вложенность в ConstraintLayout
Если используется ConstraintLayout - то никакой дополнительной вложенности не должно быть.

2020-05-05 12:10 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:orientation="vertical"
Ненужная вложенность вертикального LinearLayout в вертикальный LinearLayout

2020-05-05 12:10 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:orientation="vertical"
Ненужная вложенность вертикального LinearLayout в вертикальный LinearLayout

2020-05-05 12:10 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +    <EditText
EditText заменить на TextView

2020-05-05 12:10 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <LinearLayout
Бессмысленная вложенность LinearLayout в FrameLayout

2020-05-05 12:10 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +
Лишняя пустая строка

2020-05-05 12:10 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +        <LinearLayout
Бессмысленная вложенность вертикального LinearLayout в вертикальный LinearLayout

2020-05-05 17:26 UTC, Pavel2688 commented
Исправил замечания

2020-05-06 03:29 UTC, goblinr requested changes

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:orientation="vertical"
Не исправлено

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +            android:text="e_mail_2" />
Лишние отступы

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +
Много пустых строк

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +
Много пустых строк

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +
Много пустых строк

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/activity_main.xml
> +
Много пустых строк

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/activity_main.xml
> +
Много пустых строк

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/activity_main.xml
Много пустых строк

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +        <LinearLayout
Не исправлено

2020-05-06 03:29 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +
не исправлено

2020-05-06 09:47 UTC, Pavel2688 commented
Убрал все лишние строки и отступы

2020-05-06 10:18 UTC, goblinr requested changes

2020-05-06 10:18 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:orientation="vertical"
Ненужная вложенность вертикального LinearLayout в вертикальный LinearLayout

2020-05-06 10:18 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <LinearLayout
Бессмысленная вложенность LinearLayout в LinearLayout

2020-05-06 10:26 UTC, Pavel2688 commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <LinearLayout
В этом случае он же нужен для правильного отображения имени и номера ?

2020-05-06 10:30 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <LinearLayout
Ок, но можно было избежать лишней вложенности, если вместо родительского `LinearLayout` - использовать `ConstraintLayout` или `RelativeLayout`

2020-05-06 10:31 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <LinearLayout
Будешь переделывать? Или мне бал в твоей оценке понизить итоговой?

2020-05-06 10:33 UTC, Pavel2688 commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <LinearLayout
Переделаю лучше

2020-05-06 10:55 UTC, Pavel2688 commented
переделал на RelativeLayout

2020-05-06 10:57 UTC, goblinr requested changes

2020-05-06 10:57 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:layout_height="34dp"
Жесткие размеры для текста нужно заменить на `wrap_content` либо `match_parent`

2020-05-06 10:57 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:layout_toRightOf="@id/contactImage"
Это не верно, позиционировать текст относительно другого текста отступом. Нужно привязываться к нижнему краю `tv_name` в данном случае.

2020-05-06 10:58 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:layout_height="34dp"
Это нужно исправить везде

2020-05-06 11:10 UTC, Pavel2688 commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:layout_toRightOf="@id/contactImage"
Давайте я лучше новую тему начну делать 
А то у меня наверное еще много таких касяков)

2020-05-06 11:11 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:layout_toRightOf="@id/contactImage"
Лучше все поправь. Весь этот код войдет в курсовую. Чем он лучше изначально - тем лучше для тебя

2020-05-06 11:30 UTC, Pavel2688 commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:layout_toRightOf="@id/contactImage"
хорошо я понял поправлю

2020-05-06 12:05 UTC, Pavel2688 commented
поправил

2020-05-06 12:10 UTC, goblinr requested changes

2020-05-06 12:10 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +            android:layout_height="wrap_content"
Вот у картинки - лучше оставить жесткие размеры

2020-05-06 12:18 UTC, goblinr approved these changes
Обнови скриншоты и можно мержить

2020-05-06 12:21 UTC, Pavel2688 commented
Хорошо!!!

2020-05-06 12:31 UTC, Pavel2688 commented
![android1](https://user-images.githubusercontent.com/57447822/81176689-8c5dd180-8fb6-11ea-8392-87e6cfd66b0c.jpg)
![android2](https://user-images.githubusercontent.com/57447822/81176795-bc0cd980-8fb6-11ea-81b8-a61b75d78a9b.jpg)

2020-05-06 12:32 UTC, merged